# Generated by Django 2.2.16 on 2022-05-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=7, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Личная информация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Telegram URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vk_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='VK URL'),
        ),
    ]
