# Generated by Django 3.2 on 2022-05-17 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20220517_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=256, verbose_name='Аватар URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание события'),
        ),
    ]
