# Generated by Django 3.2 on 2022-05-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20220521_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='function',
            name='slug',
        ),
    ]
