# Generated by Django 3.2 on 2022-05-21 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20220521_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='function',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='events.function'),
            preserve_default=False,
        ),
    ]
