# Generated by Django 3.2 on 2022-05-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_follow_function'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique follow',
        ),
    ]
