# Generated by Django 3.2 on 2022-05-22 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0008_remove_follow_unique follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(help_text='событие', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='events.event')),
                ('user', models.ForeignKey(help_text='ссылка на объект пользователя, который подписывается', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='подписчик')),
            ],
        ),
    ]
