# Generated by Django 3.2 on 2022-05-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Нужное кол-во волонтеров'),
        ),
    ]
