# Generated by Django 2.2.16 on 2022-05-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20220528_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='client',
        ),
        migrations.AddField(
            model_name='event',
            name='coordinates_latitude',
            field=models.FloatField(null=True, verbose_name='Координаты (широта)'),
        ),
        migrations.AddField(
            model_name='event',
            name='coordinates_longitude',
            field=models.FloatField(null=True, verbose_name='Координаты (долгота)'),
        ),
    ]
