# Generated by Django 3.2 on 2022-05-29 15:08

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20220528_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='avatar_url',
            field=models.ImageField(upload_to=events.models.Event.event_avatar_path, verbose_name='Аватар мероприятия'),
        ),
    ]
