# Generated by Django 2.2.16 on 2022-05-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20220529_1902'),
        ('events', '0013_alter_event_avatar_url'),
    ]

    operations = [
    ]
