# Generated by Django 2.2.16 on 2022-05-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20220529_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(db_index=True, max_length=256, null=True, verbose_name='Адрес'),
        ),
    ]
