# Generated by Django 3.2 on 2022-06-17 18:12

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20220530_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='avatar_url',
            field=models.ImageField(default='events/avatars/4.png', upload_to=events.models.Event.event_avatar_path, verbose_name='Аватар мероприятия'),
        ),
    ]
