# Generated by Django 2.2.16 on 2022-05-16 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Наименование')),
                ('full_name', models.CharField(db_index=True, max_length=256, verbose_name='Полное наименование')),
                ('website', models.CharField(db_index=True, max_length=256, verbose_name='Сайт Проекта')),
                ('material_url', models.CharField(max_length=256, verbose_name='Материал')),
                ('avatar_url', models.CharField(max_length=256, verbose_name='Аватар URL')),
                ('status', models.CharField(max_length=256, verbose_name='Статус проекта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('goal', models.TextField(verbose_name='Цели')),
                ('result', models.TextField(verbose_name='Результаты')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка проекта')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Проекты',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
