# Generated by Django 3.2 on 2022-05-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220516_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=256, verbose_name='Аватар URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.TextField(blank=True, verbose_name='Цели'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='material_url',
            field=models.CharField(blank=True, max_length=256, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='project',
            name='result',
            field=models.TextField(blank=True, verbose_name='Результаты'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, max_length=256, verbose_name='Статус проекта'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
