# Generated by Django 3.2 on 2022-05-29 15:08

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20220528_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created',
        ),
        migrations.RemoveField(
            model_name='project',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='material_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='project',
            name='website',
        ),
        migrations.AlterField(
            model_name='project',
            name='avatar_url',
            field=models.ImageField(upload_to=projects.models.Project.project_avatar_path, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(choices=[('Животные', 'Животные'), ('Культура и искусство', 'Культура и искусство'), ('Здравоохранение', 'Здравоохранение'), ('Образование', 'Образование'), ('Другое', 'Другое'), ('Природа', 'Природа'), ('Поиск пропавших', 'Поиск пропавших'), ('Дети и молодежь', 'Дети и молодежь'), ('Спорт и здоровье', 'Спорт и здоровье')], db_index=True, max_length=20, verbose_name='Наименование'),
        ),
    ]
