# Generated by Django 3.2 on 2022-05-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20220529_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.TextField(blank=True, null=True, verbose_name='Цели'),
        ),
        migrations.AlterField(
            model_name='project',
            name='result',
            field=models.TextField(blank=True, null=True, verbose_name='Результаты'),
        ),
    ]
