# Generated by Django 3.2 on 2022-05-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20220529_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Наименование'),
        ),
    ]
